name: NewLifeAnalytics
version: '1.0.0'
main: com.newlife.analytics.NewLifeAnalyticsPaper
api-version: '1.20'
description: Server performance analytics and lag detection for NewLife SMP
author: NewLife SMP
